import { useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { toast } from "sonner";
import { Copy, Send, CreditCard, Loader2 } from "lucide-react";

interface CreateInvoiceDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onSuccess: () => void;
}

const CreateInvoiceDialog = ({ open, onOpenChange, onSuccess }: CreateInvoiceDialogProps) => {
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [createdInvoiceId, setCreatedInvoiceId] = useState<string | null>(null);
  const [formData, setFormData] = useState({
    customer_name: "",
    customer_email: "",
    customer_phone: "",
    service_type: "snow_removal" as "lawn_care" | "snow_removal" | "landscaping",
    job_description: "",
    amount: "",
  });

  const resetForm = () => {
    setFormData({
      customer_name: "",
      customer_email: "",
      customer_phone: "",
      service_type: "snow_removal",
      job_description: "",
      amount: "",
    });
    setCreatedInvoiceId(null);
  };

  const handleSubmit = async (action: "send" | "copy" | "charge") => {
    if (!formData.customer_name || !formData.amount) {
      toast.error("Please fill in customer name and amount");
      return;
    }

    setIsSubmitting(true);

    const { data, error } = await supabase
      .from("invoices")
      .insert({
        invoice_number: "", // Will be auto-generated by trigger
        customer_name: formData.customer_name,
        customer_email: formData.customer_email || null,
        customer_phone: formData.customer_phone || null,
        service_type: formData.service_type,
        job_description: formData.job_description || null,
        amount: parseFloat(formData.amount),
        status: action === "charge" ? "paid" : "pending",
        paid_at: action === "charge" ? new Date().toISOString() : null,
      })
      .select()
      .single();

    setIsSubmitting(false);

    if (error) {
      toast.error("Failed to create invoice");
      console.error(error);
      return;
    }

    const invoiceUrl = `${window.location.origin}/invoice/${data.id}`;

    if (action === "charge") {
      toast.success("Payment recorded successfully!");
      resetForm();
      onOpenChange(false);
      onSuccess();
    } else if (action === "copy") {
      await navigator.clipboard.writeText(invoiceUrl);
      toast.success("Invoice link copied to clipboard!");
      setCreatedInvoiceId(data.id);
    } else if (action === "send") {
      // For now, copy the link - email integration can be added later
      await navigator.clipboard.writeText(invoiceUrl);
      toast.success("Invoice created! Link copied - send via email or text.");
      setCreatedInvoiceId(data.id);
    }

    onSuccess();
  };

  const handleClose = () => {
    resetForm();
    onOpenChange(false);
  };

  const serviceLabels = {
    lawn_care: "Lawn Care",
    snow_removal: "Snow Removal",
    landscaping: "Landscaping",
  };

  return (
    <Dialog open={open} onOpenChange={handleClose}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>Create Invoice</DialogTitle>
          <DialogDescription>
            Fill in the job details and choose how to charge
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 py-4">
          <div className="space-y-2">
            <Label htmlFor="customer_name">Customer Name *</Label>
            <Input
              id="customer_name"
              placeholder="John Smith"
              value={formData.customer_name}
              onChange={(e) => setFormData(prev => ({ ...prev, customer_name: e.target.value }))}
            />
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div className="space-y-2">
              <Label htmlFor="customer_email">Email</Label>
              <Input
                id="customer_email"
                type="email"
                placeholder="john@email.com"
                value={formData.customer_email}
                onChange={(e) => setFormData(prev => ({ ...prev, customer_email: e.target.value }))}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="customer_phone">Phone</Label>
              <Input
                id="customer_phone"
                type="tel"
                placeholder="612-555-0123"
                value={formData.customer_phone}
                onChange={(e) => setFormData(prev => ({ ...prev, customer_phone: e.target.value }))}
              />
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor="service_type">Service Type</Label>
            <Select
              value={formData.service_type}
              onValueChange={(value: "lawn_care" | "snow_removal" | "landscaping") => 
                setFormData(prev => ({ ...prev, service_type: value }))
              }
            >
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="snow_removal">Snow Removal</SelectItem>
                <SelectItem value="lawn_care">Lawn Care</SelectItem>
                <SelectItem value="landscaping">Landscaping</SelectItem>
              </SelectContent>
            </Select>
          </div>

          <div className="space-y-2">
            <Label htmlFor="job_description">Job Description</Label>
            <Textarea
              id="job_description"
              placeholder="Driveway and sidewalk clearing..."
              value={formData.job_description}
              onChange={(e) => setFormData(prev => ({ ...prev, job_description: e.target.value }))}
              rows={2}
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="amount">Amount *</Label>
            <div className="relative">
              <span className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">$</span>
              <Input
                id="amount"
                type="number"
                placeholder="75.00"
                className="pl-7"
                value={formData.amount}
                onChange={(e) => setFormData(prev => ({ ...prev, amount: e.target.value }))}
              />
            </div>
          </div>
        </div>

        {createdInvoiceId && (
          <div className="bg-green-50 border border-green-200 rounded-lg p-3 text-sm text-green-800">
            ✓ Invoice created! Share the link with your customer.
          </div>
        )}

        <div className="flex flex-col gap-2 pt-2">
          <Button 
            onClick={() => handleSubmit("charge")} 
            disabled={isSubmitting}
            className="w-full gap-2"
          >
            {isSubmitting ? <Loader2 className="w-4 h-4 animate-spin" /> : <CreditCard className="w-4 h-4" />}
            Charge Now (On-Site)
          </Button>
          <div className="grid grid-cols-2 gap-2">
            <Button 
              variant="outline" 
              onClick={() => handleSubmit("copy")}
              disabled={isSubmitting}
              className="gap-2"
            >
              <Copy className="w-4 h-4" />
              Copy Link
            </Button>
            <Button 
              variant="outline" 
              onClick={() => handleSubmit("send")}
              disabled={isSubmitting}
              className="gap-2"
            >
              <Send className="w-4 h-4" />
              Send Invoice
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
};

export default CreateInvoiceDialog;
